general:
  species_name:
  reference_genome: GCF_000009045.1_ASM904v1
  mol_type: nucl
  species_list: /home/jebin/JB/Projects/pango/example/codes/accessions_b_subtilis_15.txt
blast:
  num_threads: 1
pango:
  pident: 80
  length_coverage: 80
  evalue: 1e-5
  relaxed_core: 100